name: iOS Build

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-ios:
    runs-on: macos-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4


      - name: Clone JUCE
        run: |
          git clone https://github.com/juce-framework/JUCE.git --depth 1


      - name: Build Projucer
        run: |
          cd JUCE/extras/Projucer/Builds/MacOSX
          xcodebuild -configuration Release -quiet
          sudo cp build/Release/Projucer.app/Contents/MacOS/Projucer /usr/local/bin/


      - name: Fix JUCE Module Paths
        shell: python
        run: |
          import xml.etree.ElementTree as ET
          import os

          jucer_file = "NewProject/NewProject.jucer"
          juce_modules = os.path.abspath("JUCE/modules")

          tree = ET.parse(jucer_file)
          root = tree.getroot()

          for mp in root.findall(".//MODULEPATH"):
              mp.set("path", juce_modules)

          tree.write(jucer_file)


      - name: Resave Jucer File
        run: |
          Projucer --resave NewProject/NewProject.jucer


      - name: Build iOS App
        run: |
          xcodebuild \
            -project NewProject/Builds/iOS/NewProject.xcodeproj \
            -scheme "NewProject - App" \
            -configuration Release \
            -sdk iphoneos \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO \
            clean build


      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: SkyStream-iOS
          path: |
            NewProject/Builds/iOS/build/Release-iphoneos/*.app