      - name: Configure Jucer File (Python)
        shell: python
        run: |
          import xml.etree.ElementTree as ET
          import os

          jucer_path = 'NewProject/NewProject.jucer'
          juce_modules = os.path.abspath("JUCE/modules")
          
          tree = ET.parse(jucer_path)
          root = tree.getroot()

          for mp in root.findall(".//MODULEPATH"):
              mp.set("path", juce_modules)

          export_formats = root.find('EXPORTFORMATS')
          if export_formats is not None and root.find(".//XCODE_IPHONE") is None:
              xcode_iphone = ET.SubElement(export_formats, 'XCODE_IPHONE', {
                  'targetFolder': 'Builds/iOS',
                  'appleCombinedIPHONEOS_IPHONESIMULATOR': '1',
                  'iosScreenOrientation': 'UIInterfaceOrientationPortrait',
                  'bundleIdentifier': 'com.skystream.rx' # Menambahkan ID aplikasi
              })
              configs = ET.SubElement(xcode_iphone, 'CONFIGURATIONS')
              ET.SubElement(configs, 'CONFIGURATION', {'isDebug': '1', 'name': 'Debug', 'targetName': 'SkyStream'})
              ET.SubElement(configs, 'CONFIGURATION', {'isDebug': '0', 'name': 'Release', 'targetName': 'SkyStream'})
              
              module_paths = ET.SubElement(xcode_iphone, 'MODULEPATHS')
              for mod in root.findall(".//MODULES/MODULE"):
                  mod_id = mod.get('id')
                  ET.SubElement(module_paths, 'MODULEPATH', {'id': mod_id, 'path': juce_modules})

          tree.write(jucer_path, encoding='utf-8', xml_declaration=True)

      - name: Build iOS App
        run: |
          xcodebuild -project NewProject/Builds/iOS/SkyStreamRXV2.xcodeproj \
                     -scheme "SkyStreamRXV2 - App" \
                     -configuration Release \
                     -sdk iphoneos \
                     CODE_SIGNING_ALLOWED=NO \
                     CODE_SIGNING_REQUIRED=NO \
                     ENTITLEMENTS_REQUIRED=NO \
                     AD_HOC_CODE_SIGNING_ALLOWED=YES \
                     clean build